(TeX-add-style-hook "refs"
 (lambda ()
    (LaTeX-add-bibitems
     "IEEE-1363"
     "kocher99"
     "Krasnogor2004e"
     "zjsw"
     "clzs"
     "tex"
     "companion"
     "ELIDRISSI94"
     "MELLINGER96"
     "SHELL02"
     "NPB2"
     "DPMG"
     "cnproceed"
     "cnarticle"
     "zhubajie"
     "shaheshang"
     "metamori2004"
     "FistSystem01"
     "ColdSources"
     "P2PVideoStreaming"
     "applicationoggmediatype"
     "oggencapsulationformat"
     "p2ptrafficdecline"
     "eMuleProtocolSpecification"
     "SkypeTelephonyProtocol"
     "LargeScaleLiveMedia"
     "PushbasedSceduling"
     "tinyxml"
     "THEORA"
     "VORBIS"
     "KATE")))

